name: configuration_repo_variable_workflow
on: 
  push:
  workflow_dispatch:
  
env:
  MY_NAME: "Venkat"
  
jobs:
  Test_Variables:
    runs-on: ubuntu-latest
    env:
      MY_JOB: "DevOps"
    steps:
      - name: my-step
        run: echo "$MY_NAME loves $MY_JOB with ${{vars.PROJECT_ID}}"
        env:
          MY_STEP1: "GitHub"
