name: hello-world-workflow
on: 
  workflow_dispatch:
  push:
    - main
jobs:
  my-echo-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
      - name: my-step2
        run: echo "Hello Venkat"
