name: hello-world-workflow
on: 
  push:
jobs:
  my-echo-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "This is a first step"
      - name: my-step2
        run: echo "This is a second step"
      - name: my-step3
        run: echo "This is a thrid step"
