name: testing_secret_variable_workflow
on: 
  push:
  workflow_dispatch:
  
env:
  MY_NAME: "Venkat"
  
jobs:
  Test_Variables:
    runs-on: ubuntu-latest
    env:
      MY_JOB: "DevOps"
    steps:
      - name: my-step
        run: echo "$MY_NAME loves $MY_JOB with $MY_STEP1 and secret ${{secrets.MY_SECRET}}"
        env:
          MY_STEP1: "GitHub"
