name: testing_single_variable
on: 
  push:
  workflow_dispatch:
env:
  var1 : testing1
jobs:
  test-single-variable:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "This is a first step :" $var1
      - name: my-step2
        run: echo "This is a second step :" $var2
      - name: my-step3
        run: echo "This is a thrid step"
    
    env:
      var2 : testing2
